name: cloudynode
services:
  backend:
    user: 3000:3000
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "2155:2155"
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
    restart: unless-stopped
  frontend:
    user: 3000:3000
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_HOST=${VITE_BACKEND_HOST}
    ports:
      - "2156:2156"
    depends_on:
      - backend
    restart: unless-stopped
